seed: 8888
phase: from-scratch

lightning_module:
  show_detail_every_step:
    train: 0
    valid: 1
  model:
    h: 640
    w: 640
    backbone_dict:
      name: scrfd_resv1e_34g
      in_channels: 3
      out_indices: [2, 3, 4]
    neck_dict:
      name: mm_pafpn
      in_channels: [224, 576, 736]
      out_channels: 128
      num_outs: 3
      add_extra_convs: on_output
    head_dict:
      name: scrfd_head
      head:
        n_stack: 2
        n_levels: 3
        in_channels: 128
        hid_channels: 256
        norm:
          name: GroupNorm
          num_groups: 32
          num_channels: 256
        act:
          name: ReLU
          inplace: true
        feat_share: true
        use_scale: true
      prior:
        scales: [1.0, 2.0]
        ratios: [1.0]
        base_sizes: [16, 64, 256]
        strides: [8, 16, 32]
      loss_weight:
        loc: 2.
        obj: 1.
        lmk5pt: 0.1
      nms_cfg:
        ScoreTH: 0.2
        nms_topk: 5000
        NMSTH: 0.45
    onnx_dict:
      export:
        opset_version: 11 # support better quant block
        input_names:
          - blob
        output_names:
          - box_8
          - score_8
          - lmk5pt_8
          - box_16
          - score_16
          - lmk5pt_16
          - box_32
          - score_32
          - lmk5pt_32
        # dynamic_axes:
        #   blob: { 0: "b", 2: "h", 3: "w" }
        #   box_8: { 0: "b", 2: "h", 3: "w" }
        #   score_8: { 0: "b", 2: "h", 3: "w" }
        #   lmk5pt_8: { 0: "b", 2: "h", 3: "w" }
        #   box_16: { 0: "b", 2: "h", 3: "w" }
        #   score_16: { 0: "b", 2: "h", 3: "w" }
        #   lmk5pt_16: { 0: "b", 2: "h", 3: "w" }
        #   box_32: { 0: "b", 2: "h", 3: "w" }
        #   score_32: { 0: "b", 2: "h", 3: "w" }
        #   lmk5pt_32: { 0: "b", 2: "h", 3: "w" }
        keep_initializers_as_inputs: false
      metadata:
        ColorMode: rgb
        InputSize: [1, 3, 640, 640]
        AncStrides: [[8, 8], [16, 16], [32, 32]]
        AncScales: [1, 2]
        NMSTH: 0.45
        ScoreTH: 0.5
        PadValue: 128
  dataset:
    train:
      name: DatasetFromJson
      txt_path: data/public/widerface_train/all.txt
      transforms:
        - name: ToFloat32
          keys: [image, boxes, lmk5pts]
        - name: RandomSquareCrop
          crop_choice: [0.3, 0.45, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0]
          pad_val: [128, 128, 128]
        - name: Resize
          h: 640
          w: 640
          enable_random_interpolation: true
        - name: PhotoMetricDistortion
          brightness_delta: 32
          contrast_range: [0.5, 1.5]
          saturation_range: [0.5, 1.5]
          hue_delta: 18
          gray_prob: 0.1
        - name: RandomHFlip
          prob: 0.5
        - name: Normalize
          mean: 127.5
          std: 128
          to_rgb: true
    valid:
      name: DatasetFromJson
      txt_path: data/public/widerface_val/all.txt
      transforms:
        - name: ToFloat32
          keys: [image, boxes, lmk5pts]
        - name: ResizePadIfNeed
          h: 640
          w: 640
          interpolation: BILINEAR
          pad_val: [128, 128, 128]
          pad_mode: CONSTANT
        - name: Normalize
          mean: 127.5
          std: 128
          to_rgb: true
  dataloader:
    train:
      batch_size_per_device: 32
      num_workers_per_node: 16
    valid:
      batch_size_per_device: 16
      num_workers_per_node: 4
  solvers:
    - excludes: []
      optimizer:
        name: SGD
        lr: 0.01
        momentum: 0.9
        weight_decay: 0.0005
      lr_scheduler:
        name: MultiStepLRWarmUp
        warmup_milestone: 3 # epoch
        milestones: [440, 544] # epoch
        gamma: 0.1

checkpointer:
  filename: "{epoch}-{mAP:.3f}"
  monitor: mAP
  mode: max
  verbose: true
  save_last: true
  save_top_k: -1
  save_weights_only: false

callbacks:
  - name: LearningRateMonitor
    logging_interval: step
    log_momentum: true
  - name: RichModelSummary
    max_depth: -1
  - name: RichProgressBar
    leave: true

trainer:
  precision: bf16-mixed
  max_epochs: 640
  accelerator: gpu
  devices: 1
  benchmark: false
  deterministic: true
  num_sanity_val_steps: 1
  check_val_every_n_epoch: 80

widerface_evaluation:
  onnx_pipeline_name: SCRFD
  data_folder: "data/public/widerface_evaluation/images"
  gt_folder: "data/public/widerface_evaluation/gt"
  save_results: true
